[build]
  base = "/"
  publish = "client"
  command = "echo 'No build needed - static files'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python server/server.py"
  port = 8000
  targetPort = 8000
  publish = "client"

